[package]
name = "mx5_metrics_service"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["signal", "event", "term", "fs", "ioctl", "mman"] }
log = "0.4"
env_logger = "0.11.6"
